### ISSUE TITLE
Dropped Soulbiden Items before death player

### ISSUE THREAD

**Issue by pingvikin** [DivineGenesis/BetterSoulBinding#8]
When player die with soulbidden item, this item is dropped out inventory.

## Plugin Config
"Bind Upon Craft"=[
    "antiqueatlas:empty_antique_atlas",
    "antiqueatlas:antique_atlas"
]
"Bind Upon Pickup"=[
    "antiqueatlas:empty_antique_atlas",
    "antiqueatlas:antique_atlas"
]
"Bind Upon Use"=[
    "antiqueatlas:empty_antique_atlas",
    "antiqueatlas:antique_atlas"
]
Modules {
    Permission-Check {
        Craft-Enabled=false
        KeepUponDeath-Enabled=false
        Pickup-Enabled=false
        Use-Enabled=false
    }
}

## Versions:
Forge: 2705
SpongeForge: 1.12.2-2705-7.1.0-BETA-3152
Minecraft Forge: 14.23.4.2705
Plugin: 0.10.2

## Latest log:
https://gist.github.com/pingvikin/9f8b0e8511c9a1bba0b7e84ba049de8f

## Plugins (16):
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, ActiveTime, AdminShop, EconomyLite, GriefPrevention, LuckPerms, Nucleus, Prism, Soulbound, UltimateChat, VoxelSniper, WorldEdit

## Mods (39):
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AbyssalCraft, Animania, Antique Atlas, AppleCore, Astral Sorcery, AutoRegLib, Baubles, Chameleon, ContainerFix, CraftStudio API, Cyclic, Earthworks, Embers, Example Mod, Extra Utilities 2, FastWorkbench, FoamFix, FoamFixCore, Forestry, Hardcore Darkness, Hunger Overhaul, JEI Bees, Just Enough Items, MagicBees, Magical Psi, Morpheus, Psi, Quark, Rustic, Spice of Life: Carrot Edition, Storage Drawers, Thaumcraft, Thaumic Periphery

**Comment by burpingdog1** [comment]
Are these items linked to the player BEFORE death?

**Comment by pingvikin** [comment]
yes

**Comment by burpingdog1** [comment]
Alright, sorry about the delay. Was bit busy! Will look into it right now

**Comment by burpingdog1** [comment]
I was able to replicate this with 1.12.2-2705-7.1.0-BETA-3151 (Couldn't find 3152) of sponge forge, guessing there were a few updates to the sponge which made our keep soulbound upon death code useless in the newest versions :(

**Comment by burpingdog1** [comment]
Alright, I am pretty sure I found out why. https://github.com/DivineGenesis/BetterSoulBinding/releases/tag/v0.10.3 
this should be a fix

**Comment by burpingdog1** [comment]
@pingvikin comment if it works

**Comment by pingvikin** [comment]
Bug is fixed
Good job, Thanks!
